alias s="git status"
alias b="git branch"
alias a="git add $1"
alias c="git commit $1"
alias push="git push $1"
alias p="git pull"
alias g="git log --all --decorate --oneline --graph"
alias s.="nautilus ."

alias debug="google-chrome --remote-debugging-port=9222"

alias open="xdg-open $1"
alias quiet="sudo i8kfan 0 0"
alias mid="sudo i8kfan 1 1"
alias high="sudo i8kfan 2 2"

alias ls="exa $1"
alias fd="fdfind"
alias ps="procs"
alias cat="batcat"
alias grep="rgrep"
alias space="du -sh $1"

alias tao="bluetoothctl connect 00:80:79:59:4A:E4"
alias taotao="bluetoothctl disconnect 00:80:79:59:4A:E4"
alias jab="bluetoothctl connect 50:1A:A5:36:87:00"
alias jabjab="bluetoothctl disconnect 50:1A:A5:36:87:00"
alias disk_space="ls -1 | wc -l"
